schedules:
- cron: '45 21 1-7 * 4'
  displayName: schedules
trigger:
  branches:
    include:
    - not-main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
  - task: CmdLine@2
    displayName: Command Line Script
...
